### ISSUE TITLE
What's the difference between this repo vs. conditioning set mask?

### ISSUE THREAD

**Issue by ynie** [laksjdjf/attention-couple-ComfyUI#7]
Hello, I'm new to ComfyUI and I really want to use the regional prompt from 11111 in ComfyUI. There are seem to be many options to choose from(Inspire Pack, attention couple, conditioning set mask).. what are the difference? Thanks!

**Comment by laksjdjf** [comment]
This node implements Attention mode in https://github.com/hako-mikan/sd-webui-regional-prompter. 
The conditioning set mask is in Latent mode.
I dont know Inspire Pack.

**Comment by ynie** [comment]
Thank you!
